### ISSUE TITLE
Can't cope with spaces in tags

### ISSUE THREAD

**Issue by tv42** [AnWeber/vscode-timewarrior#1]
https://timewarrior.net/docs/tutorial/ shows an example of `timew start 'Using Tags' Software`.
This makes the VSCode plugin show "5s - Software, Using, Tags" in the sidebar.
Then using the VSCode "timewarrior: Timewarrior checkin" command leads to a new entry "0s - Software, Tags, Using" (different tag order, for seemingly no reason).

The data file shows the entry started from CLI correct, the entry started from VSCode -- attempting to use previous tags -- having corrupted the tags:

```
inc 20230404T174754Z - 20230404T174832Z # Software "Using Tags"
inc 20230404T174848Z # Software Tags Using
```

**Comment by AnWeber** [comment]
I have corrected the parsing for spaces. Now the quotation marks are respected. 
The sorting is changed by `timew`. The cause is that I passed the tags Sorting, Using and Tags. These are sorted alphabetically by `timew`.
I will release a new version with v0.7.0. Have fun using it:-)
